/**
 * stateFileLoader - Bridge between Python simulation stream and React frontend
 * Reads current_state.json generated by simulate_stream.py
 * Zero network cost - pure file-based state transfer
 */

import currentState from './current_state.json';
import { TelemetryPayload } from './CryptoWrapper';

export interface SimulationMetadata {
  simulation_timestamp: number;
  cycle_count: number;
  current_milestone_id: string;
  profile_type: string;
  uptime_seconds: number;
}

export interface SystemMetrics {
  resonance: number;
  nodes_count: number;
  particle_count: number;
  fission_stretch: number;
}

export interface StatePayload {
  metadata: SimulationMetadata;
  telemetry: TelemetryPayload;
  system: SystemMetrics;
  description: string;
}

class StateFileLoader {
  private cachedState: StatePayload | null = null;
  private lastLoadTime: number = 0;
  private refreshInterval: number = 1000; // Check file every 1s

  /**
   * Get current simulation state from file
   * Caches result for refreshInterval to reduce file reads
   */
  getCurrentState(): StatePayload {
    const now = Date.now();
    
    // Return cached state if within refresh interval
    if (this.cachedState && (now - this.lastLoadTime) < this.refreshInterval) {
      return this.cachedState;
    }

    // Load fresh state from imported JSON
    // Note: In production, this would use fetch() or filesystem API
    // For now, Vite's JSON import provides hot-reload capability
    this.cachedState = currentState as StatePayload;
    this.lastLoadTime = now;

    return this.cachedState;
  }

  /**
   * Get telemetry payload ready for CryptoWrapper validation
   */
  getTelemetryPayload(): TelemetryPayload {
    const state = this.getCurrentState();
    return state.telemetry;
  }

  /**
   * Get current profile type
   */
  getProfileType(): string {
    const state = this.getCurrentState();
    return state.metadata.profile_type;
  }

  /**
   * Get particle count for canvas budget management
   */
  getParticleCount(): number {
    const state = this.getCurrentState();
    return Math.min(state.system.particle_count, 5000); // Enforce 5k budget
  }

  /**
   * Check if in fission mode (high noise state)
   */
  isFissionMode(): boolean {
    const state = this.getCurrentState();
    return state.metadata.profile_type === 'HIGH_NOISE_FISSION';
  }

  /**
   * Check if in standby mode (zero alpha state)
   */
  isStandbyMode(): boolean {
    const state = this.getCurrentState();
    return state.metadata.profile_type === 'ZERO_ALPHA_STANDBY';
  }

  /**
   * Get fission stretch factor for dumbbell morphology
   */
  getFissionStretch(): number {
    const state = this.getCurrentState();
    return state.system.fission_stretch || 0.0;
  }

  /**
   * Set refresh interval (ms)
   */
  setRefreshInterval(ms: number): void {
    this.refreshInterval = Math.max(100, ms); // Min 100ms
  }

  /**
   * Force immediate refresh on next read
   */
  invalidateCache(): void {
    this.lastLoadTime = 0;
  }

  /**
   * Get cycle count for debugging
   */
  getCycleCount(): number {
    const state = this.getCurrentState();
    return state.metadata.cycle_count;
  }

  /**
   * Get simulation uptime
   */
  getUptime(): number {
    const state = this.getCurrentState();
    return state.metadata.uptime_seconds;
  }
}

// Singleton instance for global access
export const STATE_LOADER = new StateFileLoader();

/**
 * React hook for state updates
 * Use this in components to trigger re-renders when state changes
 */
export function useSimulationState(refreshMs: number = 1000) {
  const [state, setState] = React.useState<StatePayload>(() => STATE_LOADER.getCurrentState());

  React.useEffect(() => {
    const interval = setInterval(() => {
      STATE_LOADER.invalidateCache();
      setState(STATE_LOADER.getCurrentState());
    }, refreshMs);

    return () => clearInterval(interval);
  }, [refreshMs]);

  return state;
}

// Import React for the hook
import * as React from 'react';
