/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'void-black': '#000000',
        'ignition-white': '#FFFFFF',
        'surface-charcoal': '#0A0A0A',
        'surface-dim': '#141313',
        'surface-variant': '#353434',
        'solar-amber': '#FFB300',
        'fringe-gold': '#B8860B',
        'ultranetic-amber': '#FB923C',
        'radiant-cream': '#FFF7ED',
        'physical-rose': '#F43F5E',
        'healed-sage': '#86EFAC',
        'veracity-gate-bypass': '#FF3B3B',
        'veracity-gate-active': '#FFB300',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c4c7c8',
        'on-tertiary-container': '#636565',
        'outline': '#8e9192',
        'outline-variant': '#444748',
        'primary-fixed': '#e2e2e2',
        'primary-fixed-dim': '#c6c6c7',
        'secondary': '#ffd799',
        'secondary-fixed': '#ffdeac',
        'secondary-fixed-dim': '#ffba38',
        'secondary-container': '#feb300',
        'on-secondary-container': '#6a4800',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353434',
        'surface-container-lowest': '#0e0e0e',
        'surface-bright': '#3a3939',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#5d5f5f',
        'on-primary': '#2f3131',
        'on-primary-container': '#636565',
        'on-primary-fixed': '#1a1c1c',
        'on-primary-fixed-variant': '#454747',
        'on-secondary-fixed': '#281900',
        'on-secondary-fixed-variant': '#604100',
        'on-secondary': '#432c00',
        'on-tertiary': '#2f3131',
        'on-error': '#690005',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'background': '#141313',
        'surface': '#141313',
        'primary': '#ffffff',
        'tertiary': '#ffffff',
        'tertiary-container': '#e2e2e2',
        'surface-tint': '#c6c6c7',
        'dawn-obsidian': '#0F172A',
        'deprecated-rust': '#DC2626',
      },
      fontFamily: {
        mono: ['JetBrains Mono', 'SF Mono', 'Consolas', 'monospace'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
        'status-label': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'headline-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'data-mono': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'status-label': ['10px', { lineHeight: '1', fontWeight: '700' }],
      },
      backdropBlur: {
        'xl': '20px',
      },
      backgroundColor: {
        'glass': 'rgba(255, 255, 255, 0.05)',
        'glass-dark': 'rgba(15, 23, 42, 0.7)',
      },
      borderColor: {
        'glass': 'rgba(255, 255, 255, 0.1)',
      },
      spacing: {
        'viewport-padding': '64px',
        'margin-safe': '32px',
        'unit': '4px',
        'gutter': '16px',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}